# Generated by Django 3.2.6 on 2021-08-28 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengguna', '0001_initial'),
        ('mainapp', '0004_auto_20210828_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatStudi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_instansi', models.CharField(max_length=255)),
                ('nomor_induk_studi', models.CharField(max_length=20, unique=True)),
                ('negara', models.CharField(default='INDONESIA', max_length=255)),
                ('provinsi', models.CharField(blank=True, max_length=255, null=True)),
                ('kabupaten', models.CharField(blank=True, max_length=255, null=True)),
                ('is_indonesia', models.BooleanField(default=True)),
                ('alamat_kampus_luar_negeri', models.CharField(blank=True, max_length=255, null=True)),
                ('fakultas', models.CharField(blank=True, max_length=255)),
                ('jurusan', models.CharField(blank=True, max_length=255)),
                ('jalur_masuk', models.CharField(blank=True, max_length=255, null=True)),
                ('tahun_masuk', models.DateField()),
                ('tahun_keluar', models.DateField(blank=True, null=True)),
                ('alasan_keluar', models.TextField(blank=True)),
                ('is_beasiswa', models.BooleanField(null=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengguna.pengguna')),
                ('fk_jenjang_pendidikan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.jenjangpendidikan', verbose_name='JenjangPendidikan')),
            ],
        ),
    ]
