# Generated by Django 3.2.6 on 2021-08-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayatstudi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatstudi',
            name='nama_beasiswa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='riwayatstudi',
            name='tahun_keluar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='riwayatstudi',
            name='tahun_masuk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
