# Generated by Django 3.2.6 on 2021-08-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayatstudi', '0002_auto_20210829_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayatstudi',
            name='kabupaten',
        ),
        migrations.RemoveField(
            model_name='riwayatstudi',
            name='provinsi',
        ),
        migrations.AddField(
            model_name='riwayatstudi',
            name='id_kabupaten',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riwayatstudi',
            name='id_provinsi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='riwayatstudi',
            name='nama_kabupaten',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='riwayatstudi',
            name='nama_provinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
