# Generated by Django 3.2.6 on 2021-08-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayatstudi', '0004_auto_20210829_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatstudi',
            name='alamat_kampus_luar_negeri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
