# Generated by Django 3.2.6 on 2021-08-15 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarKabupaten',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=255)),
                ('urutan', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaftarProvinsi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=255)),
                ('urutan', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenjangPendidikan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=100, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('PT', 'PERGURUAN TINGGI'), ('PMA', 'PENDIDIKAN MENENGAH ATAS')], default='', max_length=200)),
                ('urutan', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(blank=True, max_length=100, null=True)),
                ('modul', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('changes_before', models.TextField(blank=True)),
                ('changes_after', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModulInduk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode_modul', models.CharField(max_length=50)),
                ('judul_modul', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_induk_anggota', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nama_panggilan', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'LAKI-LAKI'), ('P', 'PEREMPUAN')], default='', max_length=25)),
                ('agama', models.CharField(choices=[('ISLAM', 'ISLAM'), ('KRISTEN', 'KRISTEN'), ('KATOLIK', 'KATOLIK'), ('HINDU', 'HINDU'), ('BUDDHA', 'BUDDHA'), ('KONGHUCU', 'KONGHUCU')], default='', max_length=100)),
                ('tempat_lahir', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_lahir', models.DateField()),
                ('nomor_hp', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_ijazah_tertinggi', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.jenjangpendidikan', verbose_name='Ijazah Tertinggi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipeJawabanDanPertanyaan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatStudi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_induk_studi', models.CharField(max_length=20, unique=True)),
                ('nama_instansi', models.CharField(max_length=255)),
                ('negara', models.CharField(default='INDONESIA', max_length=255)),
                ('fakultas', models.CharField(blank=True, max_length=255)),
                ('jurusan', models.CharField(blank=True, max_length=255)),
                ('tahun_masuk', models.DateField()),
                ('tahun_keluar', models.DateField(null=True)),
                ('alasan_keluar', models.TextField(blank=True)),
                ('jalur_masuk', models.CharField(blank=True, max_length=255, null=True)),
                ('is_beasiswa', models.BooleanField(null=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_jenjang_pendidikan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.jenjangpendidikan', verbose_name='JenjangPendidikan')),
                ('fk_kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kabupaten', to='mainapp.daftarkabupaten')),
                ('fk_nomor_induk_anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pengguna')),
                ('fk_provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Provinsi', to='mainapp.daftarprovinsi')),
            ],
        ),
        migrations.CreateModel(
            name='ModulPertanyaan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode_pertanyaan', models.CharField(max_length=50, unique=True)),
                ('teks_pertanyaan', models.TextField(blank=True)),
                ('urutan', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_modul_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.modulinduk')),
                ('fk_tipe_pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tipejawabandanpertanyaan')),
            ],
        ),
        migrations.CreateModel(
            name='ModulOpsiJawaban',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode_modul', models.CharField(max_length=50)),
                ('kode_kunci', models.CharField(max_length=50)),
                ('teks_jawaban', models.TextField(blank=True)),
                ('urutan', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_modul_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.modulinduk')),
                ('fk_tipe_jawaban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tipejawabandanpertanyaan')),
            ],
        ),
        migrations.AddField(
            model_name='daftarkabupaten',
            name='fk_provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.daftarprovinsi'),
        ),
    ]
