# Generated by Django 3.2.6 on 2021-08-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riwayatstudi',
            old_name='fk_nomor_induk_anggota',
            new_name='fk_anggota',
        ),
    ]
