# Generated by Django 3.2.6 on 2021-08-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_fk_nomor_induk_anggota_riwayatstudi_fk_anggota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='daftarkabupaten',
            name='fk_provinsi',
        ),
        migrations.DeleteModel(
            name='LogAktivitas',
        ),
        migrations.RemoveField(
            model_name='riwayatstudi',
            name='fk_kabupaten',
        ),
        migrations.RemoveField(
            model_name='riwayatstudi',
            name='fk_provinsi',
        ),
        migrations.AddField(
            model_name='riwayatstudi',
            name='alamat_kampus_luar_negeri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riwayatstudi',
            name='is_indonesia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riwayatstudi',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riwayatstudi',
            name='provinsi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='agama',
            field=models.CharField(blank=True, choices=[('ISLAM', 'ISLAM'), ('KRISTEN', 'KRISTEN'), ('KATOLIK', 'KATOLIK'), ('HINDU', 'HINDU'), ('BUDDHA', 'BUDDHA'), ('KONGHUCU', 'KONGHUCU')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='riwayatstudi',
            name='tahun_keluar',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DaftarKabupaten',
        ),
        migrations.DeleteModel(
            name='DaftarProvinsi',
        ),
    ]
