# Generated by Django 3.2.6 on 2021-08-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210827_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayatstudi',
            name='fk_anggota',
        ),
        migrations.RemoveField(
            model_name='riwayatstudi',
            name='fk_jenjang_pendidikan',
        ),
        migrations.DeleteModel(
            name='Pengguna',
        ),
        migrations.DeleteModel(
            name='RiwayatStudi',
        ),
    ]
