# Generated by Django 3.2.6 on 2021-08-28 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_auto_20210828_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_induk_anggota', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nama_panggilan', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'LAKI-LAKI'), ('P', 'PEREMPUAN')], default='', max_length=25)),
                ('agama', models.CharField(blank=True, choices=[('ISLAM', 'ISLAM'), ('KRISTEN', 'KRISTEN'), ('KATOLIK', 'KATOLIK'), ('HINDU', 'HINDU'), ('BUDDHA', 'BUDDHA'), ('KONGHUCU', 'KONGHUCU')], default='', max_length=100, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_lahir', models.DateField()),
                ('nomor_hp', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_ijazah_tertinggi', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.jenjangpendidikan', verbose_name='Ijazah Tertinggi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
