# Generated by Django 3.2.6 on 2021-09-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatKerja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_instansi', models.CharField(max_length=255)),
                ('alamat_instansi', models.TextField(blank=True, null=True)),
                ('bidang', models.CharField(blank=True, max_length=255)),
                ('tahun_masuk', models.CharField(blank=True, max_length=255, null=True)),
                ('tahun_keluar', models.CharField(blank=True, max_length=255, null=True)),
                ('alasan_keluar', models.TextField(blank=True)),
                ('jabatan', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.TextField(blank=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengguna.pengguna')),
            ],
        ),
    ]
