# Generated by Django 3.2.6 on 2021-09-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayatkerja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatkerja',
            name='bidang',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
